"""Канонические строки клининг-контура."""

from decimal import Decimal

CLEANING_PAYMENT_METHODS = ["Наличные", "Карта", "Расчётный"]
CLEANING_GIFT_CERT_LABEL = "Подарочный сертификат"
CLEANING_ALL_PAYMENT_LABELS = CLEANING_PAYMENT_METHODS + [CLEANING_GIFT_CERT_LABEL]

CLEANING_EXPENSE_CATEGORIES = ["Химия", "ЗП клинеров", "ГСМ", "Прочее"]

CLEANING_DIVIDEND_METHOD = "Касса клининга"

CASHBOOK_KIND_INCOME = "income"
CASHBOOK_KIND_EXPENSE = "expense"
CASHBOOK_KIND_DIVIDEND = "dividend"
CASHBOOK_KIND_WITHDRAWAL = "withdrawal"
CASHBOOK_KIND_DEPOSIT = "deposit"

CASHBOOK_KINDS_INCREASE_BALANCE = {CASHBOOK_KIND_INCOME, CASHBOOK_KIND_DEPOSIT}
CASHBOOK_KINDS_DECREASE_BALANCE = {
    CASHBOOK_KIND_EXPENSE,
    CASHBOOK_KIND_DIVIDEND,
    CASHBOOK_KIND_WITHDRAWAL,
}
CASHBOOK_KINDS_PNL = {CASHBOOK_KIND_INCOME, CASHBOOK_KIND_EXPENSE}

ZERO = Decimal("0")
